data_load:
  dataset_csv: "data/coffee_shop_revenue.csv"
featurize:
  features_path: "data/final.csv"
data_split:
  test_size: 0.3
  trainset_path: "data/train_revenue.csv"
  testset_path: "data/test_revenue.csv"
train:
  cv: 4
  model_type: "tree"
  alpha: [0.0001, 0.001, 0.01, 0.05, 0.5]
  n_estimators: [800]
  model_path: "models/revenue.joblib"
  power_path: "models/power.joblib"
test:
  model_path: "models/revenue.joblib"
  power_path: "models/power.joblib"
  testset_path: "data/test_revenue.csv"
  
